-- Generated by Oracle SQL Developer REST Data Services 19.2.1.247.2212
-- Exported REST Definitions from ORDS Schema Version 19.2.0.r1991647
-- Schema: ERP_DEVELOPMENT   Date: Fri Jan 24 17:25:33 EST 2020
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ERP_DEVELOPMENT',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'db',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'genLedger',
      p_base_path      => '/gl/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'acct',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'acct',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  gl_acct_id
    ,   acct_desc
    ,   acct_type
    ,   dt_deleted
    ,   user_id
    ,   dt_edited
FROM erp_gl_account
WHERE gl_acct_id = :inAcctId'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'GET',
      p_name               => 'inAcctId',
      p_bind_variable_name => 'inAcctId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'acct',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    UPDATE erp_gl_account
    SET     gl_acct_id  = :inAcctId
        ,   acct_desc   = :inAcctDesc
        ,   acct_type   = :inAcctType
        ,   user_id     = :inUserId
        ,   change_dt   = SYSDATE
    WHERE gl_acct_id = :inAcctId;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'PUT',
      p_name               => 'inAcctDesc',
      p_bind_variable_name => 'inAcctDesc',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'PUT',
      p_name               => 'inAcctId',
      p_bind_variable_name => 'inAcctId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'PUT',
      p_name               => 'inAcctType',
      p_bind_variable_name => 'inAcctType',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'PUT',
      p_name               => 'inUserId',
      p_bind_variable_name => 'inUserId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'acct',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO erp_gl_account
    VALUES  (       :inAcctId
                ,   :inAcctDesc
                ,   :inAcctType
                ,   NULL
                ,   :inUserId
                ,   SYSDATE
            );
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'POST',
      p_name               => 'inAcctDesc',
      p_bind_variable_name => 'inAcctDesc',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'POST',
      p_name               => 'inAcctId',
      p_bind_variable_name => 'inAcctId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'POST',
      p_name               => 'inAcctType',
      p_bind_variable_name => 'inAcctType',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'POST',
      p_name               => 'inUserId',
      p_bind_variable_name => 'inUserId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'acctList',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'acctList',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  gl_acct_id
    ,   acct_desc
    ,   acct_type
    ,   user_id
    ,   dt_edited
FROM erp_gl_account'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'bank',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'bank',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
        bank_id
    ,   gl_acct_id
    ,   bank_title
    ,   bank_desc
    ,   bank_acct_no
    ,   TO_CHAR(checkbook_dt, ''YYYYMMDD'')
    ,   TO_CHAR(statement_dt, ''YYYYMMDD'')
    ,   bank_year
    ,   bank_period
    ,   bank_name
    ,   bank_addr1
    ,   bank_addr2
    ,   bank_city
    ,   bank_state
    ,   bank_zip_code
    ,   bank_contact
    ,   bank_phone_no
    ,   bank_fax_no
    ,   bank_country
    ,   remit_name
    ,   remit_addr1
    ,   remit_addr2
    ,   remit_city
    ,   remit_state
    ,   remit_zip_code
    ,   remit_contact
    ,   remit_phone_no
    ,   remit_fax_no
    ,   remit_country
    ,   next_check_no
    ,   balance
    ,   notes_collected
    ,   interest
    ,   nsf_payments
    ,   overstated_deposits
    ,   misc_charges
    ,   stmt_balance
    ,   deposits_intransit
    ,   misc_plus
    ,   misc_minus
    ,   TO_CHAR(dt_deleted, ''YYYYMMDD'')
    ,   user_id
    ,   TO_CHAR(dt_edited, ''YYYYMMDD'')
    ,   notes
FROM erp_gl_bank
WHERE bank_id = :inBankId'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'GET',
      p_name               => 'inBankId',
      p_bind_variable_name => 'inBankId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'bank',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    UPDATE erp_gl_bank
    SET     bank_id             = :inBankId
        ,   gl_acct_id          = :inAcctId
        ,   bank_title          = :inBankTitle
        ,   bank_desc           = :inBankDesc
        ,   bank_acct_no        = :inBankAcctNo
        ,   checkbook_dt        = TO_DATE(:inCheckbookDt, ''YYYYMMDD'')
        ,   statment_dt         = TO_DATE(:inStatementDt, ''YYYYMMDD'')
        ,   bank_year           = :inBankYear
        ,   bank_period         = :inBankPeriod
        ,   bank_name           = :inBankName
        ,   bank_addr1          = :inBankAddr1
        ,   bank_addr2          = :inBankAddr2
        ,   bank_city           = :inBankCity
        ,   bank_state          = :inBankState
        ,   bank_zip_code       = :inBankZipCode
        ,   bank_contact        = :inBankContact
        ,   bank_phone_no       = :inBankPhoneNo
        ,   bank_fax_no         = :inBankFaxNo
        ,   bank_country        = :inBankCountry
        ,   remit_name          = :inRemitName
        ,   remit_addr1         = :inRemitAddr1
        ,   remit_addr2         = :inRemitAddr2
        ,   remit_city          = :inRemitCity
        ,   remit_state         = :inRemitState
        ,   remit_zip_code      = :inRemitZipCode
        ,   remit_contract      = :inRemitContact
        ,   remit_phone_no      = :inRemitPhoneNo
        ,   remit_fax_no        = :inRemitFaxNo
        ,   remit_country       = :inRemitCountry
        ,   next_check_no       = :inNextCheckNo
        ,   balance             = :inBalance
        ,   notes_collected     = :inNotesCollected
        ,   interest            = :inInterest
        ,   nsf_payments        = :inNsfPayments
        ,   overstated_deposits = :inOverstatedDeposits
        ,   misc_charges        = :inMiscCharges
        ,   stmt_balance        = :inStmtBalance
        ,   deposits_intransit  = :inDepositsIntransit
        ,   misc_plus           = :inMiscPlus
        ,   misc_minus          = :inMiscMinus
        ,   user_id             = :inUserId
        ,   dt_updated          = SYSDATE
        ,   notes               = :inNotes
    WHERE bank_id = :inBankId;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inAcctId',
      p_bind_variable_name => 'inAcctId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBalance',
      p_bind_variable_name => 'inBalance',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankAcctNo',
      p_bind_variable_name => 'inBankAcctNo',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankAddr1',
      p_bind_variable_name => 'inBankAddr1',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankAddr2',
      p_bind_variable_name => 'inBankAddr2',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankCity',
      p_bind_variable_name => 'inBankCity',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankContact',
      p_bind_variable_name => 'inBankContact',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankCountry',
      p_bind_variable_name => 'inBankCountry',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankDesc',
      p_bind_variable_name => 'inBankDesc',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankFaxNo',
      p_bind_variable_name => 'inBankFaxNo',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankId',
      p_bind_variable_name => 'inBankId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankName',
      p_bind_variable_name => 'inBankName',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankPeriod',
      p_bind_variable_name => 'inBankPeriod',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankPhoneNo',
      p_bind_variable_name => 'inBankPhoneNO',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankState',
      p_bind_variable_name => 'inBankState',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankTitle',
      p_bind_variable_name => 'inBankTitle',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankYear',
      p_bind_variable_name => 'inBankYear',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inBankZipCode',
      p_bind_variable_name => 'inBankZipCode',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inCheckbookDt',
      p_bind_variable_name => 'inCheckbookDt',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inInterest',
      p_bind_variable_name => 'inInterest',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inMiscMinus',
      p_bind_variable_name => 'inMiscMinus',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inMiscPlus',
      p_bind_variable_name => 'inMiscPlus',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inNextCheckNo',
      p_bind_variable_name => 'inNextCheckNo',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inNotes',
      p_bind_variable_name => 'inNotes',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inNotesCollected',
      p_bind_variable_name => 'inNotesCollected',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inNsfPayments',
      p_bind_variable_name => 'inNsfPayments',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inOverstatedDeposits',
      p_bind_variable_name => 'inOverstatedDeposits',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inRemitAddr1',
      p_bind_variable_name => 'inRemitAddr1',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inRemitAddr2',
      p_bind_variable_name => 'inRemitAddr2',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inRemitCity',
      p_bind_variable_name => 'inRemitCity',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inRemitContact',
      p_bind_variable_name => 'inRemitContact',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inRemitCountry',
      p_bind_variable_name => 'inRemitCountry',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inRemitFaxNo',
      p_bind_variable_name => 'inRemitFaxNo',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inRemitName',
      p_bind_variable_name => 'inRemitName',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inRemitPhoneNo',
      p_bind_variable_name => 'inRemitPhoneNo',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inRemitState',
      p_bind_variable_name => 'inRemitState',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inRemitZipCode',
      p_bind_variable_name => 'inRemitZipCode',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inStatementDt',
      p_bind_variable_name => 'inStatementDt',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'PUT',
      p_name               => 'inUserId',
      p_bind_variable_name => 'inUserId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'bank',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO erp_gl_bank
    VALUES  (       :inBankId
                ,   :inAcctId
                ,   :inBankTitle
                ,   :inBankDesc
                ,   :inBankAcctNo
                ,   TO_DATE(:inCheckbookDt, ''YYYYMMDD'')
                ,   TO_DATE(:inStatementDt, ''YYYYMMDD'')
                ,   :inBankYear
                ,   :inBankPeriod
                ,   :inBankName
                ,   :inBankAddr1
                ,   :inBankAddr2
                ,   :inBankCity
                ,   :inBankState
                ,   :inBankZipCode
                ,   :inBankContact
                ,   :inBankPhoneNo
                ,   :inBankFaxNo
                ,   :inBankCountry
                ,   :inRemitName
                ,   :inRemitAddr1
                ,   :inRemitAddr2
                ,   :inRemitCity
                ,   :inRemitState
                ,   :inRemitZipCode
                ,   :inRemitContact
                ,   :inRemitPhoneNo
                ,   :inRemitFaxNo
                ,   :inRemitCountry
                ,   :inNextCheckNo
                ,   :inBalance
                ,   :inNotesCollected
                ,   :inInterest
                ,   :inNsfPayments
                ,   :inOverstatedDeposits
                ,   :inMiscCharges
                ,   :inStmtBalance
                ,   :inDepositsIntransit
                ,   :inMiscPlus
                ,   :inMiscMinus
                ,   NULL
                ,   :inUserId
                ,   SYSDATE
                ,   :inNotes
        );
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inAcctId',
      p_bind_variable_name => 'inAcctId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBalance',
      p_bind_variable_name => 'inBalance',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankAcctNo',
      p_bind_variable_name => 'inBankAcctNo',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankAddr1',
      p_bind_variable_name => 'inBankAddr1',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankAddr2',
      p_bind_variable_name => 'inBankAddr2',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankCity',
      p_bind_variable_name => 'inBankCity',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankContact',
      p_bind_variable_name => 'inBankContact',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankCountry',
      p_bind_variable_name => 'inBankCountry',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankDesc',
      p_bind_variable_name => 'inBankDesc',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankFaxNo',
      p_bind_variable_name => 'inBankFaxNo',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankId',
      p_bind_variable_name => 'inBankId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankName',
      p_bind_variable_name => 'inBankName',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankPeriod',
      p_bind_variable_name => 'inBankPeriod',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankPhoneNo',
      p_bind_variable_name => 'inBankPhoneNo',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankState',
      p_bind_variable_name => 'inBankState',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankTitle',
      p_bind_variable_name => 'inBankTitle',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankYear',
      p_bind_variable_name => 'inBankYear',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inBankZipCode',
      p_bind_variable_name => 'inBankZipCode',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inCheckbookDt',
      p_bind_variable_name => 'inCheckbookDt',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inDepositsIntransit',
      p_bind_variable_name => 'inDepositsIntransit',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inInterest',
      p_bind_variable_name => 'inInterest',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inMiscCharges',
      p_bind_variable_name => 'inMiscCharges',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inMiscMinus',
      p_bind_variable_name => 'inMiscMinus',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inMiscPlus',
      p_bind_variable_name => 'inMiscPlus',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inNextCheckNo',
      p_bind_variable_name => 'inNextCheckNo',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inNotes',
      p_bind_variable_name => 'inNotes',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inNotesCollected',
      p_bind_variable_name => 'inNotesCollected',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inNsfPayments',
      p_bind_variable_name => 'inNsfPayments',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inOverstatedDeposits',
      p_bind_variable_name => 'inOverstatedDeposits',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inRemitAddr1',
      p_bind_variable_name => 'inRemitAddr1',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inRemitAddr2',
      p_bind_variable_name => 'inRemitAddr2',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inRemitCity',
      p_bind_variable_name => 'inRemitCity',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inRemitContact',
      p_bind_variable_name => 'inRemitContact',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inRemitCountry',
      p_bind_variable_name => 'inRemitCountry',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inRemitFaxNo',
      p_bind_variable_name => 'inRemitFaxNo',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inRemitName',
      p_bind_variable_name => 'inRemitName',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inRemitPhoneNo',
      p_bind_variable_name => 'inRemitPhoneNo',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inRemitState',
      p_bind_variable_name => 'inRemitState',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inRemitZipCode',
      p_bind_variable_name => 'inRemitZipCode',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inStatementDt',
      p_bind_variable_name => 'inStatementDt',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inStmtBalance',
      p_bind_variable_name => 'inStmtBalance',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'inUserId',
      p_bind_variable_name => 'inUserId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'bankList',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'bankList',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  bank_id
    ,   gl_acct_id
    ,   bank_title
    ,   bank_desc
    ,   bank_acct_no
    ,   TO_CHAR(checkbook_dt, ''MM-DD-YYYY'')
    ,   TO_CHAR(statement_dt, ''MM-DD-YYYY'')
    ,   bank_year
    ,   bank_period
    ,   bank_name
    ,   bank_addr1
    ,   bank_addr2
    ,   bank_city
    ,   bank_state
    ,   bank_zip_code
    ,   bank_contact
    ,   bank_phone_no
    ,   bank_fax_no
    ,   bank_country
    ,   remit_name
    ,   remit_addr1
    ,   remit_addr2
    ,   remit_city
    ,   remit_state
    ,   remit_zip_code
    ,   remit_contact
    ,   remit_phone_no
    ,   remit_fax_no
    ,   remit_country
    ,   next_check_no
    ,   balance
    ,   notes_collected
    ,   interest
    ,   nsf_payments
    ,   overstated_deposits
    ,   misc_charges
    ,   stmt_balance
    ,   deposits_intransit
    ,   misc_plus
    ,   misc_minus
    ,   dt_deleted
    ,   user_id
    ,   dt_updated
    ,   notes
FROM erp_gl_bank'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'batch',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'batch',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  batch_id
    ,   TO_CHAR(dt_created, ''YYYYMMDD'')
    ,   TO_CHAR(dt_posted, ''YYYYMMDD'')
    ,   source_module
    ,   post_error
    ,   user_id
    ,   dt_updated
FROM erp_gl_batch
WHERE batch_id = :inBatchId'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'batch',
      p_method             => 'GET',
      p_name               => 'inBatchId',
      p_bind_variable_name => 'inBatchId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'batch',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    UPDATE erp_gl_batch
    SET     batch_id        = :inBatchId
        ,   dt_created      = TO_DATE(:inDtCreated, ''YYYYMMDD'')
        ,   dt_posted       = TO_DATE(:inDtPosted, ''YYYYMMDD'')
        ,   source_module   = :inSourceModule
        ,   post_error      = :inPostError
        ,   user_id         = :inUserId
        ,   dt_updated      = TO_DATE(:inDtUpdated, ''YYYYMMDD'')
    WHERE batch_id = :inBatchId;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'batch',
      p_method             => 'PUT',
      p_name               => 'inBatchId',
      p_bind_variable_name => 'inBatchId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'batch',
      p_method             => 'PUT',
      p_name               => 'inDtCreated',
      p_bind_variable_name => 'inDtCreated',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'batch',
      p_method             => 'PUT',
      p_name               => 'inDtPosted',
      p_bind_variable_name => 'inDtPosted',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'batch',
      p_method             => 'PUT',
      p_name               => 'inDtUpdated',
      p_bind_variable_name => 'inDtUpdated',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'batch',
      p_method             => 'PUT',
      p_name               => 'inPostError',
      p_bind_variable_name => 'inPostError',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'batch',
      p_method             => 'PUT',
      p_name               => 'inSourceModule',
      p_bind_variable_name => 'inSourceModule',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'batch',
      p_method             => 'PUT',
      p_name               => 'inUserId',
      p_bind_variable_name => 'inUserId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'batch',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO erp_gl_batch
    VALUES
        (       :inBatchId
            ,   SYSDATE
            ,   NULL
            ,   :inSourceModule
            ,   :inPostError
            ,   :inUserId
            ,   SYSDATE
        );
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'batch',
      p_method             => 'POST',
      p_name               => 'inBatchId',
      p_bind_variable_name => 'inBatchId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'batch',
      p_method             => 'POST',
      p_name               => 'inPostError',
      p_bind_variable_name => 'inPostError',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'batch',
      p_method             => 'POST',
      p_name               => 'inSourceModule',
      p_bind_variable_name => 'inSourceModule',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'batch',
      p_method             => 'POST',
      p_name               => 'inUserId',
      p_bind_variable_name => 'inUserId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlEntry',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlEntry',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  batch_id
    ,   batch_trans_id
    ,   gl_acct_id
    ,   amount
    ,   user_id
    ,   TO_CHAR(dt_posted, ''YYYYMMDD'')
    ,   TO_CHAR(dt_updated, ''YYYYMMDD'')
FROM erp_gl_pending_detail
WHERE batch_id          = :inBatchId
  AND batch_trans_id    = :inBatchTransId'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlEntry',
      p_method             => 'GET',
      p_name               => 'inBatchId',
      p_bind_variable_name => 'inBatchId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlEntry',
      p_method             => 'GET',
      p_name               => 'inBatchTransId',
      p_bind_variable_name => 'inBatchTransId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlEntry',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    UPDATE erp_gl_journal_detail
    SET     batch_id        = :inBatchId
        ,   batch_trans_id  = :inBatchTransId
        ,   gl_acct_id      = :inAcctId
        ,   amount          = :inAmount
        ,   user_id         = :inUserId
        ,   dt_posted       = TO_DATE(:inDtPosted, ''YYYYMMDD'')
        ,   dt_updated      = SYSDATE
    WHERE batch_id      = :inBatchId
      AND batch_tran_id = :inBatchTranId;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlEntry',
      p_method             => 'PUT',
      p_name               => 'inAcctId',
      p_bind_variable_name => 'inAcctId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlEntry',
      p_method             => 'PUT',
      p_name               => 'inAmount',
      p_bind_variable_name => 'inAmount',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlEntry',
      p_method             => 'PUT',
      p_name               => 'inBatchId',
      p_bind_variable_name => 'inBatchId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlEntry',
      p_method             => 'PUT',
      p_name               => 'inBatchTransId',
      p_bind_variable_name => 'inBatchTransId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlEntry',
      p_method             => 'PUT',
      p_name               => 'inDtPosted',
      p_bind_variable_name => 'inDtPosted',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlEntry',
      p_method             => 'PUT',
      p_name               => 'inUserId',
      p_bind_variable_name => 'inUserId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlEntry',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO erp_gl_pending_detail
    VALUES
    (       :inBatchId
        ,   :inBatchTransId
        ,   :inAcctId
        ,   :inAmount
        ,   :inUserId
        ,   NULL
        ,   SYSDATE
    );
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlEntry',
      p_method             => 'POST',
      p_name               => 'inAcctId',
      p_bind_variable_name => 'inAcctId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlEntry',
      p_method             => 'POST',
      p_name               => 'inAmount',
      p_bind_variable_name => 'inAmount',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlEntry',
      p_method             => 'POST',
      p_name               => 'inBatchId',
      p_bind_variable_name => 'inBatchId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlEntry',
      p_method             => 'POST',
      p_name               => 'inBatchTransId',
      p_bind_variable_name => 'inBatchTransId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlEntry',
      p_method             => 'POST',
      p_name               => 'inUserId',
      p_bind_variable_name => 'inUserId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlHead',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlHead',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  batch_id
    ,   batch_trans_id
    ,   trans_year
    ,   trans_period
    ,   TO_CHAR(entry_dt, ''YYYYMMDD'')
    ,   TO_CHAR(transaction_dt, ''YYYYMMDD'')
    ,   journal_type_id
    ,   user_id
    ,   TO_CHAR(dt_updated, ''YYYYMMDD'')
    ,   TO_CHAR(dt_posted, ''YYYYMMDD'')
    ,   trans_reference
    ,   trans_desc
FROM erp_gl_journal_header
WHERE batch_id          = :inBatchId
  AND batch_trans_id    = :inBatchTransId'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'GET',
      p_name               => 'inBatchId',
      p_bind_variable_name => 'inBatchId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'GET',
      p_name               => 'inBatchTransId',
      p_bind_variable_name => 'inBatchTransId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlHead',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    UPDATE erp_gl_journal_header
    SET     batch_id        = :inBatchId
        ,   batch_trans_id  = :inBatchTransId
        ,   trans_year      = :inTransYear
        ,   trans_period    = :inTransPeriod
        ,   entry_dt        = TO_DATE(:inEntryDt, ''YYYYMMDD'')
        ,   transaction_dt  = TO_DATE(:inTransactionDt, ''YYYYMMDD'')
        ,   journal_type_id = :inJournalTypeId
        ,   user_id         = :inUserId
        ,   dt_updated      = SYSDATE
        ,   dt_posted       = TO_DATE(:inDtPosted, ''YYYYMMDD'')
        ,   trans_reference = :inTransReference
        ,   trans_desc      = :inTransDesc
    WHERE batch_id      = :inBatchId
      AND batch_tran_id = :inBatchTranId;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'PUT',
      p_name               => 'inBatchId',
      p_bind_variable_name => 'inBatchId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'PUT',
      p_name               => 'inBatchTransId',
      p_bind_variable_name => 'inBatchTransId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'PUT',
      p_name               => 'inDtPosted',
      p_bind_variable_name => 'inDtPosted',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'PUT',
      p_name               => 'inEntryDt',
      p_bind_variable_name => 'inEntryDt',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'PUT',
      p_name               => 'inJournalTypeId',
      p_bind_variable_name => 'inJournalTypeId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'PUT',
      p_name               => 'inTransDesc',
      p_bind_variable_name => 'inTransDesc',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'PUT',
      p_name               => 'inTransPeriod',
      p_bind_variable_name => 'inTransPeriod',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'PUT',
      p_name               => 'inTransReference',
      p_bind_variable_name => 'inTransReference',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'PUT',
      p_name               => 'inTransYear',
      p_bind_variable_name => 'inTransYear',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'PUT',
      p_name               => 'inTransactionDt',
      p_bind_variable_name => 'inTransactionDt',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'PUT',
      p_name               => 'inUserId',
      p_bind_variable_name => 'inUserId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlHead',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO erp_gl_journal_header
    VALUES
    (       :inBatchId
        ,   :inBatchTransId
        ,   :inTransYear
        ,   :inTransPeriod
        ,   TO_DATE(:inEntryDt, ''YYYYMMDD'')
        ,   TO_DATE(:inTransactionDt, ''YYYYMMDD'')
        ,   :inJournalTypeId
        ,   :inUserId
        ,   SYSDATE
        ,   :inTransReference
        ,   :inTransDesc
    );
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'POST',
      p_name               => 'inBatchId',
      p_bind_variable_name => 'inBatchId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'POST',
      p_name               => 'inBatchTransId',
      p_bind_variable_name => 'inBatchTransId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'POST',
      p_name               => 'inEntryDt',
      p_bind_variable_name => 'inEntryDt',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'POST',
      p_name               => 'inJournalTypeId',
      p_bind_variable_name => 'inJournalTypeId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'POST',
      p_name               => 'inTransDesc',
      p_bind_variable_name => 'inTransDesc',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'POST',
      p_name               => 'inTransPeriod',
      p_bind_variable_name => 'inTransPeriod',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'POST',
      p_name               => 'inTransReference',
      p_bind_variable_name => 'inTransReference',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'POST',
      p_name               => 'inTransYear',
      p_bind_variable_name => 'inTransYear',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'POST',
      p_name               => 'inTransactionDt',
      p_bind_variable_name => 'inTransactionDt',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlHead',
      p_method             => 'POST',
      p_name               => 'inUserId',
      p_bind_variable_name => 'inUserId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlType',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlType',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  journal_type_id
    ,   journal_type_desc
    ,   user_id
    ,   dt_updated
FROM    erp_gl_journal_type
WHERE dt_deleted IS NULL
  AND journal_type_id = :inJournalTypeId'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlType',
      p_method             => 'GET',
      p_name               => 'inJournalTypeId',
      p_bind_variable_name => 'inJournalTypeId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlType',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    UPDATE erp_gl_journal_type
    SET     journal_type_id     = :inJournalTypeId
        ,   journal_type_desc   = :inJournalTypeDesc
        ,   user_id             = :inUserId
        ,   dt_updated          = SYSDATE
        ,   dt_deleted          = TO_DATE(:inDtDeleted, ''YYYYMMDD'')
    WHERE journal_type_id = :inJournalTypeId;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlType',
      p_method             => 'PUT',
      p_name               => 'inDtDeleted',
      p_bind_variable_name => 'inDtDeleted',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlType',
      p_method             => 'PUT',
      p_name               => 'inJournalTypeDesc',
      p_bind_variable_name => 'inJournalTypeDesc',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlType',
      p_method             => 'PUT',
      p_name               => 'inJournalTypeId',
      p_bind_variable_name => 'inJournalTypeId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlType',
      p_method             => 'PUT',
      p_name               => 'inUserId',
      p_bind_variable_name => 'inUserId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlType',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO erp_gl_journal_type
    VALUES
        (       NULL
            ,   :inJournalTypeDesc
            ,   :inUserId
            ,   SYSDATE
            ,   NULL
        );
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlType',
      p_method             => 'POST',
      p_name               => 'inJournalTypeDesc',
      p_bind_variable_name => 'inJournalTypeDesc',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlType',
      p_method             => 'POST',
      p_name               => 'inUserId',
      p_bind_variable_name => 'inUserId',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlTypeList',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlTypeList',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  journal_type_id
    ,   journal_type_desc
    ,   user_id
    ,   dt_updated
FROM    erp_gl_journal_type
WHERE dt_deleted IS NULL'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'newBatchID',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'newBatchID',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  new_batch_id()  batch_id,
        1               batch_trans_id
FROM dual'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'newTransID',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'newTransID',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT new_batch_trans_id(:inBatchId)    batch_trans_id
FROM dual'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'newTransID',
      p_method             => 'GET',
      p_name               => 'inBatchId',
      p_bind_variable_name => 'inBatchId',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'trans',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'trans',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  batch_id
    ,   batch_trans_id
    ,   gl_acct_id
    ,   gl_trans_year
    ,   gl_trans_period
    ,   clt_ven_id
    ,   clt_ven_type
    ,   trans_reference
    ,   reference_type
    ,   TO_CHAR(transaction_dt, ''YYYYMMDD'')
    ,   invoice_ref
    ,   amount
    ,   user_id
    ,   TO_CHAR(dt_posted, ''YYYYMMDD'')
    ,   TO_CHAR(dt_updated, ''YYYYMMDD'')
FROM erp_gl_transaction
WHERE batch_id          = :inBatchID
  AND batch_trans_id    = :inBatchTransID'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'GET',
      p_name               => 'inBatchID',
      p_bind_variable_name => 'inBatchID',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'GET',
      p_name               => 'inBatchTransID',
      p_bind_variable_name => 'inBatchTransID',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'trans',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    UPDATE erp_gl_transaction
    SET     batch_id        = :inBatchID
        ,   batch_trans_id  = :inBatchTransID
        ,   gl_acct_id      = :inAcctID
        ,   gl_trans_year   = :inTransYear
        ,   gl_trans_period = :inTransPeriod
        ,   clt_ven_id      = :inCltVenID
        ,   clt_ven_type    = :inCltVenType
        ,   trans_reference = :inTransReference
        ,   reference_type  = :inReferenceType
        ,   transaction_dt  = TO_DATE(:inTransactionDt, ''YYYYMMDD'')
        ,   invoice_ref     = :inInvoiceRef
        ,   amount          = :inAmount
        ,   user_id         = :inUserID
        ,   dt_posted       = TO_DATE(:inDtPosted, ''YYYYMMDD'')
        ,   dt_updated      = SYSDATE
    WHERE batch_id          = :inBatchID
      AND batch_trans_id    = :inBatchTransID
      AND gl_acct_id        = :inAcctID;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'PUT',
      p_name               => 'inAcctID',
      p_bind_variable_name => 'inAcctID',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'PUT',
      p_name               => 'inAmount',
      p_bind_variable_name => 'inAmount',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'PUT',
      p_name               => 'inBatchID',
      p_bind_variable_name => 'inBatchID',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'PUT',
      p_name               => 'inBatchTransID',
      p_bind_variable_name => 'inBatchTransID',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'PUT',
      p_name               => 'inCltVenID',
      p_bind_variable_name => 'inCltVenID',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'PUT',
      p_name               => 'inCltVenType',
      p_bind_variable_name => 'inCltVenType',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'PUT',
      p_name               => 'inDtPosted',
      p_bind_variable_name => 'inDtPosted',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'PUT',
      p_name               => 'inInvoiceRef',
      p_bind_variable_name => 'inInvoiceRef',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'PUT',
      p_name               => 'inReferenceType',
      p_bind_variable_name => 'inReferenceType',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'PUT',
      p_name               => 'inTransPeriod',
      p_bind_variable_name => 'inTransPeriod',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'PUT',
      p_name               => 'inTransReference',
      p_bind_variable_name => 'inTransReference',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'PUT',
      p_name               => 'inTransYear',
      p_bind_variable_name => 'inTransYear',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'PUT',
      p_name               => 'inTransactionDt',
      p_bind_variable_name => 'inTransactionDt',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'PUT',
      p_name               => 'inUserID',
      p_bind_variable_name => 'inUserID',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'trans',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO erp_gl_transaction
    VALUES (:inBatchID
        ,   :inBatchTransID
        ,   :inAcctID
        ,   :inTransYear
        ,   :inTransPeriod
        ,   :inCltVenID
        ,   :inCltVenType
        ,   :inTransReference
        ,   :inReferenceType
        ,   TO_DATE(:inTransactionDt, ''YYYYMMDD'')
        ,   :inInvoiceRef
        ,   :inAmount
        ,   :inUserID
        ,   TO_DATE(:inDtPosted, ''YYYYMMDD'')
        ,   SYSDATE
    );
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'POST',
      p_name               => 'inAcctID',
      p_bind_variable_name => 'inAcctID',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'POST',
      p_name               => 'inAmount',
      p_bind_variable_name => 'inAmount',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'POST',
      p_name               => 'inBatchID',
      p_bind_variable_name => 'inBatchID',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'POST',
      p_name               => 'inBatchTransID',
      p_bind_variable_name => 'inBatchTransID',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'POST',
      p_name               => 'inCltVenID',
      p_bind_variable_name => 'inCltVenID',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'POST',
      p_name               => 'inCltVenType',
      p_bind_variable_name => 'inCltVenType',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'POST',
      p_name               => 'inDtPosted',
      p_bind_variable_name => 'inDtPosted',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'POST',
      p_name               => 'inInvoiceRef',
      p_bind_variable_name => 'inInvoiceRef',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'POST',
      p_name               => 'inReferenceType',
      p_bind_variable_name => 'inReferenceType',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'POST',
      p_name               => 'inTransPeriod',
      p_bind_variable_name => 'inTransPeriod',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'POST',
      p_name               => 'inTransReference',
      p_bind_variable_name => 'inTransReference',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'POST',
      p_name               => 'inTransYear',
      p_bind_variable_name => 'inTransYear',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'POST',
      p_name               => 'inTransactionDt',
      p_bind_variable_name => 'inTransactionDt',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'trans',
      p_method             => 'POST',
      p_name               => 'inUserID',
      p_bind_variable_name => 'inUserID',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      


  COMMIT; 
END;