-- Generated by Oracle SQL Developer REST Data Services 19.2.1.247.2212
-- Exported REST Definitions from ORDS Schema Version 19.2.0.r1991647
-- Schema: ERP_DEVELOPMENT   Date: Mon Jan 20 17:12:26 EST 2020
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ERP_DEVELOPMENT',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'db',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'genLedger',
      p_base_path      => '/gl/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'acct',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'acct',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    UPDATE erp_gl_account SET
            gl_acct_id = :gl_acct_id
        ,   descript = :descript
        ,   acct_type = :acct_type
        ,   change_user = :change_user
        ,   change_dt = SYSDATE
    WHERE gl_acct_id = :gl_acct_id;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'PUT',
      p_name               => 'acct_type',
      p_bind_variable_name => 'acct_type',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'PUT',
      p_name               => 'change_user',
      p_bind_variable_name => 'change_user',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'PUT',
      p_name               => 'descript',
      p_bind_variable_name => 'descript',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'PUT',
      p_name               => 'gl_acct_id',
      p_bind_variable_name => 'gl_acct_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'acct',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  gl_acct_id
        , descript
        , acct_type
        , change_user
        , change_dt
FROM erp_gl_account
WHERE gl_acct_id = :acct_id'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'GET',
      p_name               => 'acct_id',
      p_bind_variable_name => 'acct_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'acct',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO erp_gl_account
    VALUES  (   :gl_acct_id
                , :descript
                , :acct_type
                , :change_user
                , SYSDATE
            );
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'POST',
      p_name               => 'acct_type',
      p_bind_variable_name => 'acct_type',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'POST',
      p_name               => 'change_user',
      p_bind_variable_name => 'change_user',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'POST',
      p_name               => 'descript',
      p_bind_variable_name => 'descript',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'acct',
      p_method             => 'POST',
      p_name               => 'gl_acct_id',
      p_bind_variable_name => 'gl_acct_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'acctlist',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'acctlist',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  gl_acct_id
        , descript
        , acct_type
        , change_user
        , change_dt
FROM erp_gl_account'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'bank',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'bank',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
        bank_id
    ,   gl_acct_id
    ,   descript
    ,   bank_acct_num
    ,   checkbook_dt
    ,   statement_dt
    ,   year
    ,   period
    ,   bank_name
    ,   address1
    ,   address2
    ,   city
    ,   state
    ,   zip_code
    ,   contact
    ,   phone_no
    ,   fax_no
    ,   country
    ,   remit_name
    ,   remit_addr1
    ,   remit_addr2
    ,   remit_city
    ,   remit_state
    ,   remit_zip_code
    ,   remit_contact
    ,   remit_phone_no
    ,   remit_fax_no
    ,   remit_country
    ,   next_check_no
    ,   balance
    ,   notes_collected
    ,   interest
    ,   nsf_payments
    ,   overstated_deposits
    ,   misc_charges
    ,   stmt_balance
    ,   deposits_intransit
    ,   misc_plus
    ,   misc_minus
    ,   notes
FROM erp_gl_bank
WHERE bank_id = :bank_id'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'GET',
      p_name               => 'bank_id',
      p_bind_variable_name => 'bank_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'bank',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO erp_gl_bank VALUES
        (       :bank_id
            ,   :gl_acct_id
            ,   :descript
            ,   :bank_acct_no
            ,   TO_DATE(:checkbook_dt, ''MM-DD-YYYY'')
            ,   TO_DATE(:statement_dt, ''MM-DD-YYYY'')
            ,   :year
            ,   :period
            ,   :bank_name
            ,   :address1
            ,   :address2
            ,   :city
            ,   :state
            ,   :zip_code
            ,   :contact
            ,   :phone_no
            ,   :fax_no
            ,   :country
            ,   :remit_name
            ,   :remit_addr1
            ,   :remit_addr2
            ,   :remit_city
            ,   :remit_state
            ,   :remit_zip_code
            ,   :remit_contact
            ,   :remit_phone_no
            ,   :remit_fax_no
            ,   :remit_country
            ,   :next_check_no
            ,   :balance
            ,   :notes_collected
            ,   :interest
            ,   :nsf_payments
            ,   :overstated_deposits
            ,   :misc_charges
            ,   :stmt_balance
            ,   :deposits_intransit
            ,   :misc_plus
            ,   :misc_minus
            ,   :change_user
            ,   SYSDATE
            ,   :notes
        );
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'address1',
      p_bind_variable_name => 'address1',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'address2',
      p_bind_variable_name => 'address2',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'balance',
      p_bind_variable_name => 'balance',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'bank_acct_no',
      p_bind_variable_name => 'bank_acct_no',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'bank_id',
      p_bind_variable_name => 'bank_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'bank_name',
      p_bind_variable_name => 'bank_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'change_user',
      p_bind_variable_name => 'change_user',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'checkbook_dt',
      p_bind_variable_name => 'checkbook_dt',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'city',
      p_bind_variable_name => 'city',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'contact',
      p_bind_variable_name => 'contact',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'country',
      p_bind_variable_name => 'country',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'deposits_intransit',
      p_bind_variable_name => 'deposits_intransit',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'descript',
      p_bind_variable_name => 'descript',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'fax_no',
      p_bind_variable_name => 'fax_no',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'gl_acct_id',
      p_bind_variable_name => 'gl_acct_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'interest',
      p_bind_variable_name => 'interest',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'misc_charges',
      p_bind_variable_name => 'misc_charges',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'misc_minus',
      p_bind_variable_name => 'misc_minus',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'misc_plus',
      p_bind_variable_name => 'misc_plus',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'next_check_no',
      p_bind_variable_name => 'next_check_no',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'notes',
      p_bind_variable_name => 'notes',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'notes_collected',
      p_bind_variable_name => 'notes_collected',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'nsf_payments',
      p_bind_variable_name => 'nsf_payments',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'overstated_deposits',
      p_bind_variable_name => 'overstated_deposits',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'period',
      p_bind_variable_name => 'period',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'phone_no',
      p_bind_variable_name => 'phone_no',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'remit_addr1',
      p_bind_variable_name => 'remit_addr1',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'remit_addr2',
      p_bind_variable_name => 'remit_addr2',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'remit_city',
      p_bind_variable_name => 'remit_city',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'remit_contact',
      p_bind_variable_name => 'remit_contact',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'remit_country',
      p_bind_variable_name => 'remit_country',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'remit_fax_no',
      p_bind_variable_name => 'remit_fax_no',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'remit_name',
      p_bind_variable_name => 'remit_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'remit_phone_no',
      p_bind_variable_name => 'remit_phone_no',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'remit_state',
      p_bind_variable_name => 'remit_state',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'remit_zip_code',
      p_bind_variable_name => 'remit_zip_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'state',
      p_bind_variable_name => 'state',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'statement_dt',
      p_bind_variable_name => 'statement_dt',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'stmt_balance',
      p_bind_variable_name => 'stmt_balance',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'year',
      p_bind_variable_name => 'year',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'bank',
      p_method             => 'POST',
      p_name               => 'zip_code',
      p_bind_variable_name => 'zip_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'banklist',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'banklist',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  bank_id
    ,   gl_acct_id
    ,   descript
    ,   bank_acct_num
    ,   checkbook_dt
    ,   statement_dt
    ,   year
    ,   period
    ,   bank_name
    ,   address1
    ,   address2
    ,   city
    ,   state
    ,   zip_code
    ,   contact
    ,   phone_no
    ,   fax_no
    ,   country
    ,   remit_name
    ,   remit_addr1
    ,   remit_addr2
    ,   remit_city
    ,   remit_state
    ,   remit_zip_code
    ,   remit_contact
    ,   remit_phone_no
    ,   remit_fax_no
    ,   remit_country
    ,   next_check_no
    ,   balance
    ,   notes_collected
    ,   interest
    ,   nsf_payments
    ,   overstated_deposits
    ,   misc_charges
    ,   stmt_balance
    ,   deposits_intransit
    ,   misc_plus
    ,   misc_minus
    ,   notes
FROM erp_gl_bank'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlentry',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlentry',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  batch_id
    ,   batch_tran_id
    ,   gl_acct_id
    ,   amount
    ,   user_id
    ,   dt_added
FROM erp_gl_pending_detail
WHERE batch_id      = :batch_id
  AND batch_tran_id = :batch_tran_id'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlentry',
      p_method             => 'GET',
      p_name               => 'batch_id',
      p_bind_variable_name => 'batch_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlentry',
      p_method             => 'GET',
      p_name               => 'batch_tran_id',
      p_bind_variable_name => 'batch_tran_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlentry',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO erp_gl_pending_detail
    VALUES
    (       :batch_id
        ,   :batch_tran_id
        ,   :gl_acct_id
        ,   :amount
        ,   :user_id
        ,   SYSDATE
    );
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlentry',
      p_method             => 'POST',
      p_name               => 'amount',
      p_bind_variable_name => 'amount',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlentry',
      p_method             => 'POST',
      p_name               => 'batch_id',
      p_bind_variable_name => 'batch_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlentry',
      p_method             => 'POST',
      p_name               => 'batch_tran_id',
      p_bind_variable_name => 'batch_tran_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlentry',
      p_method             => 'POST',
      p_name               => 'gl_acct_id',
      p_bind_variable_name => 'gl_acct_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlentry',
      p_method             => 'POST',
      p_name               => 'user_id',
      p_bind_variable_name => 'user_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlheadent',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlheadent',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  batch_id
    ,   batch_tran_id
    ,   yr
    ,   period
    ,   entry_dt
    ,   transaction_dt
    ,   journal_type_id
    ,   user_id
    ,   dt_added
    ,   refer
    ,   descript
FROM erp_gl_pending_header
WHERE batch_id      = :batch_id
  AND batch_tran_id = :batch_tran_id'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlheadent',
      p_method             => 'GET',
      p_name               => 'batch_id',
      p_bind_variable_name => 'batch_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlheadent',
      p_method             => 'GET',
      p_name               => 'batch_tran_id',
      p_bind_variable_name => 'batch_tran_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnlheadent',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO erp_gl_pending_header
    VALUES
    (       :batch_id
        ,   :batch_tran_id
        ,   :yr
        ,   :period
        ,   :entry_dt
        ,   :transaction_dt
        ,   :journal_type_id
        ,   :user_id
        ,   SYSDATE
        ,   :refer
        ,   :descript
    );
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlheadent',
      p_method             => 'POST',
      p_name               => 'batch_id',
      p_bind_variable_name => 'batch_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlheadent',
      p_method             => 'POST',
      p_name               => 'batch_tran_id',
      p_bind_variable_name => 'batch_tran_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlheadent',
      p_method             => 'POST',
      p_name               => 'descript',
      p_bind_variable_name => 'descript',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlheadent',
      p_method             => 'POST',
      p_name               => 'entry_dt',
      p_bind_variable_name => 'entry_dt',
      p_source_type        => 'HEADER',
      p_param_type         => 'TIMESTAMP',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlheadent',
      p_method             => 'POST',
      p_name               => 'journal_type_id',
      p_bind_variable_name => 'journal_type_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlheadent',
      p_method             => 'POST',
      p_name               => 'period',
      p_bind_variable_name => 'period',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlheadent',
      p_method             => 'POST',
      p_name               => 'refer',
      p_bind_variable_name => 'refer',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlheadent',
      p_method             => 'POST',
      p_name               => 'transaction_dt',
      p_bind_variable_name => 'transaction_dt',
      p_source_type        => 'HEADER',
      p_param_type         => 'TIMESTAMP',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlheadent',
      p_method             => 'POST',
      p_name               => 'user_id',
      p_bind_variable_name => 'user_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnlheadent',
      p_method             => 'POST',
      p_name               => 'yr',
      p_bind_variable_name => 'yr',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnltype',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnltype',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    UPDATE erp_gl_journal_type
    SET     journal_type_id = :type_id
        ,   descript = :descript
        ,   active  = :active
        ,   change_user = :change_user
        ,   change_dt   = SYSDATE
    WHERE journal_type_id = :journal_type_id;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnltype',
      p_method             => 'PUT',
      p_name               => 'active',
      p_bind_variable_name => 'active',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnltype',
      p_method             => 'PUT',
      p_name               => 'change_user',
      p_bind_variable_name => 'change_user',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnltype',
      p_method             => 'PUT',
      p_name               => 'descript',
      p_bind_variable_name => 'descript',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnltype',
      p_method             => 'PUT',
      p_name               => 'type_id',
      p_bind_variable_name => 'type_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnltype',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  journal_type_id
    ,   descript
    ,   active
    ,   change_user
    ,   change_dt
FROM    erp_gl_journal_type
WHERE active = ''Y''
  AND journal_type_id = :type_id'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnltype',
      p_method             => 'GET',
      p_name               => 'type_id',
      p_bind_variable_name => 'type_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnltype',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    INSERT INTO erp_gl_journal_type VALUES
        (       NULL
            ,   :descript
            ,   ''Y''
            ,   :change_user
            ,   SYSDATE
        );
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnltype',
      p_method             => 'POST',
      p_name               => 'change_user',
      p_bind_variable_name => 'change_user',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'genLedger',
      p_pattern            => 'jrnltype',
      p_method             => 'POST',
      p_name               => 'descript',
      p_bind_variable_name => 'descript',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnltypelist',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'genLedger',
      p_pattern        => 'jrnltypelist',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT  journal_type_id
    ,   descript
    ,   active
    ,   change_user
    ,   change_dt
FROM    erp_gl_journal_type
WHERE active = ''Y'''
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'genLedger',
      p_pattern        => 'post2jrnl',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);


  COMMIT; 
END;